### ISSUE TITLE
toSimplified 中將"呼叫"转换成"唿叫"

### ISSUE THREAD

**Issue by Joshua1986** [berniey/hanziconv#16]
复现代码：
`python
from hanziconv import HanziConv
print(HanziConv.toSimplified('呼叫'))
`
预期结果："呼叫"
实际结果："唿叫"

**Comment by loretoparisi** [comment]
@Joshua1986  I have fixed it now it should be ok

```python
print(HanziConv.toSimplified("呼叫"))
# 呼叫
```

**Comment by chen-yingfa** [comment]
@loretoparisi As of version `hanziconv-0.3.2` (installed using pip), this issue is not solved.
```python
>>> s = '呼叫'
>>> print(HanziConv.toTraditional(s))
呼叫
>>> print(HanziConv.toSimplified(s))
唿叫
```
